# Generated by Django 5.2.8 on 2025-12-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='upload_to',
        ),
        migrations.AddField(
            model_name='emails',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emails',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
