# Generated by Django 5.2.8 on 2025-12-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_alter_student_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=1000)),
                ('salary', models.FloatField()),
                ('retirement', models.IntegerField()),
                ('other_benefits', models.CharField(max_length=10000)),
                ('total_benifits', models.CharField()),
                ('total_compensation', models.CharField()),
            ],
        ),
    ]
