# Generated by Django 5.2.8 on 2025-12-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='total_benifits',
            new_name='total_benefits',
        ),
    ]
