# Generated by Django 5.2.8 on 2025-12-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_rename_total_benifits_employee_total_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='retirement',
            field=models.FloatField(),
        ),
    ]
