# Generated by Django 5.2.8 on 2025-12-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0005_alter_employee_retirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(),
        ),
    ]
