# Generated by Django 5.2.8 on 2025-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0006_employee_id_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_benefits',
            field=models.CharField(),
        ),
    ]
