# Generated by Django 5.2.8 on 2025-12-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0007_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='roll',
        ),
    ]
