# Generated by Django 5.2.8 on 2025-12-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0008_rename_roll_number_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
