# Generated by Django 5.2.8 on 2025-12-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0009_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(null=True),
        ),
    ]
