# Generated by Django 5.2.8 on 2025-12-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0010_remove_customer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
