# Generated by Django 5.2.8 on 2025-12-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0011_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
