# Generated by Django 5.2.8 on 2025-12-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0012_alter_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
