# Generated by Django 5.2.8 on 2025-12-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0013_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
