# Generated by Django 5.2.8 on 2025-12-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0014_upload_file_model_alter_student_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='importdata/'),
        ),
    ]
