# Generated by Django 5.2.8 on 2025-12-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0015_alter_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='import-data/'),
        ),
    ]
